name: Unit tests

on:

  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Install JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run unit tests
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: test

    - name: Add coverage report to Pages site
      run: |
        export REV=$(git rev-parse --short HEAD)
        git config pull.rebase false
        git config user.email git@github.com
        git config user.name 'GitHub Actions'
        git fetch
        git checkout -b gh-pages --track origin/gh-pages
        git pull
        mv ktest/build/reports/jacoco/test/html docs/$REV
        git add -f docs
        git commit -m "$(echo -e "📝 test coverage for $REV\nhttps://haliphax.github.io/ktest/$REV")"
        git push -u origin gh-pages
